version: '3.0'
services:
  backend:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ../../env/.env.development.local
    environment:
      - NODE_ENV=development
    ports:
      - 10010:80
    networks:
      - backend
    restart: always
    volumes:
      - ../../_data/upload:/app/_data/upload
      - ../../_data/img:/app/_data/img

  mysql:
    image: 'mysql:5.7'
    stdin_open: true
    tty: true
    env_file:
      - ../../env/.env.development.local
    environment:
      - TZ=Asia/Seoul
    ports:
      - 10020:3306
    networks:
      - backend
    restart: always
    volumes:
      - ../../_data/mysql:/var/lib/mysql

networks:
  backend: