stages:
  - test
  - deploy

# test
api-test:
  stage: test
  image: docker
  services:
    - docker:dind

  before_script:
    - apk add --no-cache docker-compose

  script:
    - cd docker/test && docker-compose -p kbj_node up --build --abort-on-container-exit

  only:
    - dev
    - master

# dev deploy
deploy-dev:
  stage: deploy
  image: ubuntu

  before_script:
    - apt update -y
    - apt install -y sshpass rsync

  script:
    - rsync --rsh="sshpass -p $DEV_PASSWORD ssh -o StrictHostKeyChecking=no -l $DEV_USER"
        -chav --delete --filter=":- .gitignore" --exclude .git/ 
        ./ $DEV_USER@$DEV_HOST:$DEV_PATH
    - sshpass -p $DEV_PASSWORD ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_HOST 
        "cd $DEV_PATH/docker/development && docker-compose -p kbj_node up -d --build"

  only:
    - master
