stages:
  - test
  - deploy

# test
api-test:
  stage: test
  image: docker
  services:
    - docker:dind

  before_script:
    - apk add --no-cache docker-compose

  script:
    - cd docker/test && docker-compose -p kbj_node up --build --abort-on-container-exit

  only:
    - dev
    - master

# dev deploy
deploy-dev:
  stage: deploy
  image: ubuntu

  before_script:
    - apt update -y
    - apt install -y sshpass rsync

  script:
    - rsync --rsh="sshpass -p kbjnodebackend ssh -o StrictHostKeyChecking=no -l root"
        -chav --delete --filter=":- .gitignore" --exclude .git/ 
        ./ root@132.145.95.10:/project/kbj-node-backend
    - sshpass -p kbjnodebackend ssh -o StrictHostKeyChecking=no root@132.145.95.10 
        "cd /project/kbj-node-backend/docker/development && docker-compose -p kbj_node up -d --build"

  only:
    - master
