const _ = require('lodash');
const { db } = require('../../database/models');

module.exports = async ({ data, user, transaction }) => {
  const {
    id,
    type,
    subject,
    createAuth,
    createLevel,
    createRole,
    readListAuth,
    readListLevel,
    readListRole,
    readAuth,
    readLevel,
    readRole,
    updateAuth,
    updateLevel,
    updateRole,
    deleteAuth,
    deleteLevel,
    deleteRole,
    likeAuth,
    likeLevel,
    likeRole,
    useComment,
    commentCreateAuth,
    commentCreateLevel,
    commentCreateRole,
    commentReadListAuth,
    commentReadListLevel,
    commentReadListRole,
    commentDeleteAuth,
    commentDeleteLevel,
    commentDeleteRole,
    commentLikeAuth,
    commentLikeLevel,
    commentLikeRole,
    fileCreateAuth,
    fileCreateLevel,
    fileCreateRole,
    fileReadAuth,
    fileReadLevel,
    fileReadRole,
    attachImageSize,
    attachFileSize,
    attachFileSizeTotal,
  } = data;

  const [newItem, isCreated] = await db.BoardSetting.findOrCreate({
    where: { type },
    defaults: _.omitBy(
      {
        id,
        userId: user.userId,
        type,
        subject,
        createAuth,
        createLevel,
        createRole,
        readListAuth,
        readListLevel,
        readListRole,
        readAuth,
        readLevel,
        readRole,
        updateAuth,
        updateLevel,
        updateRole,
        deleteAuth,
        deleteLevel,
        deleteRole,
        likeAuth,
        likeLevel,
        likeRole,
        useComment,
        commentCreateAuth,
        commentCreateLevel,
        commentCreateRole,
        commentReadListAuth,
        commentReadListLevel,
        commentReadListRole,
        commentDeleteAuth,
        commentDeleteLevel,
        commentDeleteRole,
        commentLikeAuth,
        commentLikeLevel,
        commentLikeRole,
        fileCreateAuth,
        fileCreateLevel,
        fileCreateRole,
        fileReadAuth,
        fileReadLevel,
        fileReadRole,
        attachImageSize,
        attachFileSize,
        attachFileSizeTotal,
      },
      _.isUndefined,
    ),
    transaction,
  });

  return { item: newItem, isCreated };
};
